export const homeData = {
  nav: [
    { href: "#services", label: "Focus" },
    { href: "#projects-preview", label: "Projects" },
    { href: "#stack", label: "Stack" },
    { href: "contacts.html", label: "Contact" },
  ],
  heroPoints: ["Go backend", "REST and gRPC APIs", "PostgreSQL", "Docker", "Kafka basics"],
  sideCards: [
    {
      label: "Role target",
      title: "Junior+/Middle Go Backend",
      text: "Focused on backend roles where API design, databases, services, and delivery quality matter.",
    },
    {
      label: "Recruiter signal",
      title: "Portfolio with code proof",
      text: "Each highlighted project links to a repository and explains what technical reviewers can inspect.",
    },
  ],
  recruiterSnapshot: [
    ["Target role", "Go Backend Developer"],
    ["Best evidence", "3 public backend repositories"],
    ["Core strengths", "APIs, PostgreSQL, Docker, service boundaries"],
    ["Contact path", "Email, LinkedIn, hh.ru, GitHub, Telegram"],
  ],
  profileItems: [
    "Open to backend roles and project discussions",
    "Go, PostgreSQL, REST, gRPC, Docker",
    "Can discuss architecture decisions in English or Russian",
    "Portfolio is built around public repositories",
  ],
  features: [
    ["01", "Backend Product APIs", "Building REST and gRPC services with clear request flow, predictable error handling, and contracts that are easy to test and extend."],
    ["02", "Database-backed Services", "Designing PostgreSQL schemas, queries, and persistence layers for product features that need reliable data behavior."],
    ["03", "Service Structure", "Keeping routing, business logic, storage, configuration, and delivery concerns separated so another engineer can follow the code."],
    ["04", "Containerized Delivery", "Using Docker and documented startup flows so projects are easier to review, run locally, and prepare for deployment."],
    ["05", "Integration Workflows", "Working with external APIs, parsing, background jobs, and data normalization behind stable backend contracts."],
    ["06", "Async Communication", "Exploring Kafka, events, and gRPC service communication for systems that move beyond a single-process API."],
  ],
  differentiators: [
    ["Repository-first portfolio", "The site does not ask recruiters to trust a claim first. It points them to code, project boundaries, and review paths."],
    ["Backend-specific evidence", "Instead of relying on UI screenshots, the portfolio highlights API contracts, database choices, service flow, integration work, and delivery setup."],
    ["Interview-ready explanations", "Project summaries are written so a recruiter can screen quickly and a technical interviewer can ask concrete follow-up questions."],
  ],
  previewProjects: [
    {
      icon: "images/wise.png",
      alt: "Task tracker API illustration",
      pill: "REST API",
      title: "Task Tracker API",
      text: "A Go REST API that demonstrates authenticated task management, PostgreSQL persistence, layered service structure, and Docker startup.",
      repo: "https://github.com/denterion/golang-Tack-tracker",
      items: ["JWT authentication flow", "PostgreSQL task model", "Swagger and Docker review path"],
    },
    {
      icon: "images/eternity.png",
      alt: "Job aggregator illustration",
      pill: "Data aggregation",
      title: "Job Aggregator",
      text: "A Go service focused on collecting external job data, normalizing inconsistent inputs, and returning cleaner search-oriented output.",
      repo: "https://github.com/denterion/job-aggregator",
      items: ["Source-specific ingestion", "Shared vacancy model", "Filtering-friendly output"],
    },
    {
      icon: "images/flower.png",
      alt: "Event-driven notification platform illustration",
      pill: "Event-driven platform",
      title: "Event-Driven Notification Platform",
      text: "A Go backend project organized around Kafka events, gRPC communication, and delivery workflows across service boundaries.",
      repo: "https://github.com/denterion/Event-Driven-Notification-Platform",
      items: ["Kafka event flow", "gRPC service boundary", "Notification delivery workflow"],
    },
  ],
  principles: [
    ["Readable architecture", "Code should be understandable from its structure, naming, and boundaries, not only from explanations in an interview."],
    ["Reviewable delivery", "A portfolio project should be easy to open, run, and inspect, because recruiters and engineers have limited time."],
    ["Practical abstractions", "I prefer simple layers and explicit flows over complexity that looks impressive but slows down maintenance."],
    ["Long-term maintainability", "Good backend code should be realistic to debug, extend, and hand over to another engineer."],
  ],
  process: [
    ["01", "Clarify the system boundary", "Define the service responsibility, the core flows, and the interfaces that matter before implementation grows in the wrong direction."],
    ["02", "Model data and behavior", "Shape the API, database structure, and service contracts together so the implementation does not fight the domain model later."],
    ["03", "Implement with operational context", "Add logging, clear service flow, and delivery conventions early instead of treating operations as an afterthought."],
    ["04", "Keep the result extensible", "Make future changes possible by keeping code paths understandable and design choices explicit."],
  ],
  stackGroups: [
    ["Languages and runtime", ["Go", "SQL", "Bash", "JavaScript"]],
    ["Data and storage", ["PostgreSQL", "Schema design", "Query design"]],
    ["Interfaces", ["REST", "gRPC", "JWT", "Swagger"]],
    ["Infrastructure and delivery", ["Docker", "Compose", "Service logging"]],
    ["Messaging and workflows", ["Kafka", "Schedulers", "External APIs"]],
  ],
};
